[
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/51349036",
    "html_url": "https://github.com/electron/electron/issues/553#issuecomment-51349036",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/553",
    "id": 51349036,
    "user": {
      "login": "zcbenz",
      "id": 639601,
      "avatar_url": "https://avatars3.githubusercontent.com/u/639601?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zcbenz",
      "html_url": "https://github.com/zcbenz",
      "followers_url": "https://api.github.com/users/zcbenz/followers",
      "following_url": "https://api.github.com/users/zcbenz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zcbenz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zcbenz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zcbenz/subscriptions",
      "organizations_url": "https://api.github.com/users/zcbenz/orgs",
      "repos_url": "https://api.github.com/users/zcbenz/repos",
      "events_url": "https://api.github.com/users/zcbenz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zcbenz/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2014-08-06T15:15:44Z",
    "updated_at": "2014-08-06T15:15:44Z",
    "body": "Can you remove the `external_binaries` directory and run `./script/bootstrap.py` again?\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/51364905",
    "html_url": "https://github.com/electron/electron/issues/553#issuecomment-51364905",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/553",
    "id": 51364905,
    "user": {
      "login": "sryze",
      "id": 4525736,
      "avatar_url": "https://avatars0.githubusercontent.com/u/4525736?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sryze",
      "html_url": "https://github.com/sryze",
      "followers_url": "https://api.github.com/users/sryze/followers",
      "following_url": "https://api.github.com/users/sryze/following{/other_user}",
      "gists_url": "https://api.github.com/users/sryze/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sryze/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sryze/subscriptions",
      "organizations_url": "https://api.github.com/users/sryze/orgs",
      "repos_url": "https://api.github.com/users/sryze/repos",
      "events_url": "https://api.github.com/users/sryze/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sryze/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-08-06T17:04:18Z",
    "updated_at": "2014-08-06T17:04:18Z",
    "body": "OK, I tried running script/bootstrap.py multiple times but same error popped up over and over again (sorry, I must have overlooked it):\n\n```\nTraceback (most recent call last):\n  File \"script\\update-external-binaries.py\", line 66, in <module>\n    sys.exit(main())\n  File \"script\\update-external-binaries.py\", line 34, in main\n    download_and_unzip('directxsdk')\n  File \"script\\update-external-binaries.py\", line 52, in download_and_unzip\n    extract_zip(zip_path, 'external_binaries')\n  File \"C:\\Users\\***\\Sources\\atom-shell\\script\\lib\\util.py\", line 72, in extract_zip\n    with zipfile.ZipFile(zip_path) as z:\n  File \"C:\\Python27\\lib\\zipfile.py\", line 770, in __init__\n    self._RealGetContents()\n  File \"C:\\Python27\\lib\\zipfile.py\", line 839, in _RealGetContents\n    raise BadZipfile(\"Bad magic number for central directory\")\nzipfile.BadZipfile: Bad magic number for central directory\nTraceback (most recent call last):\n  File \"C:\\Users\\***\\Sources\\atom-shell\\script\\update.py\", line 47, in <module>\n    sys.exit(main())\n  File \"C:\\Users\\***\\Sources\\atom-shell\\script\\update.py\", line 16, in main\n    update_external_binaries()\n  File \"C:\\Users\\***\\Sources\\atom-shell\\script\\update.py\", line 22, in update_external_bin\naries\n    subprocess.check_call([sys.executable, uf])\n  File \"C:\\Python27\\lib\\subprocess.py\", line 540, in check_call\n    raise CalledProcessError(retcode, cmd)\nsubprocess.CalledProcessError: Command '['C:\\\\Python27\\\\python.exe', 'script\\\\update-exter\nnal-binaries.py']' returned non-zero exit status 1\n\nTraceback (most recent call last):\n  File \"script/bootstrap.py\", line 116, in <module>\n    sys.exit(main())\n  File \"script/bootstrap.py\", line 33, in main\n    update_atom_shell()\n  File \"script/bootstrap.py\", line 112, in update_atom_shell\n    execute([sys.executable, update])\n  File \"C:\\Users\\***\\Sources\\atom-shell\\script\\lib\\util.py\", line 120, in execute\n    raise e\nsubprocess.CalledProcessError: Command '['C:\\\\Python27\\\\python.exe', 'C:\\\\Users\\\\***\\\\Sour\nces\\\\atom-shell\\\\script\\\\update.py']' returned non-zero exit status 1\n```\n\nDownloading directxsdk.zip and vs2012_crt.zip manually helped though.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/51365323",
    "html_url": "https://github.com/electron/electron/issues/553#issuecomment-51365323",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/553",
    "id": 51365323,
    "user": {
      "login": "sryze",
      "id": 4525736,
      "avatar_url": "https://avatars0.githubusercontent.com/u/4525736?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sryze",
      "html_url": "https://github.com/sryze",
      "followers_url": "https://api.github.com/users/sryze/followers",
      "following_url": "https://api.github.com/users/sryze/following{/other_user}",
      "gists_url": "https://api.github.com/users/sryze/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sryze/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sryze/subscriptions",
      "organizations_url": "https://api.github.com/users/sryze/orgs",
      "repos_url": "https://api.github.com/users/sryze/repos",
      "events_url": "https://api.github.com/users/sryze/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sryze/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-08-06T17:07:31Z",
    "updated_at": "2014-08-06T17:07:31Z",
    "body": "Now I'm getting a link error:\n\n```\n[994/994] LINK_EMBED atom.exe\nFAILED: C:\\Python27\\python.exe gyp-win-tool link-with-manifests environment.x86 True atom.\nexe \"C:\\Python27\\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nolo\ngo /OUT:atom.exe @atom.exe.rsp\" 1 mt.exe rc.exe \"obj\\atom.atom.exe.intermediate.manifest\"\nobj\\atom.atom.exe.generated.manifest\natls.lib(atlbase.obj) : error LNK2005: \"class ATL::CAtlWinModule ATL::_AtlWinModule\" (?_At\nlWinModule@ATL@@3VCAtlWinModule@1@A) already defined in chromiumviews.lib(views.native_vie\nw_accessibility_win.obj)\natom.exe : fatal error LNK1169: one or more multiply defined symbols found\nTraceback (most recent call last):\n  File \"gyp-win-tool\", line 315, in <module>\n    sys.exit(main(sys.argv[1:]))\n  File \"gyp-win-tool\", line 29, in main\n    exit_code = executor.Dispatch(args)\n  File \"gyp-win-tool\", line 71, in Dispatch\n    return getattr(self, method)(*args[1:])\n  File \"gyp-win-tool\", line 169, in ExecLinkWithManifests\n    subprocess.check_call(ldcmd + add_to_ld)\n  File \"C:\\Python27\\lib\\subprocess.py\", line 540, in check_call\n    raise CalledProcessError(retcode, cmd)\nsubprocess.CalledProcessError: Command 'C:\\Python27\\python.exe gyp-win-tool link-wrapper e\nnvironment.x86 False link.exe /nologo /OUT:atom.exe @atom.exe.rsp atom.exe.manifest.res' r\neturned non-zero exit status 1169\nninja: build stopped: subcommand failed.\n```\n\nShould I create a new issue?\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/51476854",
    "html_url": "https://github.com/electron/electron/issues/553#issuecomment-51476854",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/553",
    "id": 51476854,
    "user": {
      "login": "zcbenz",
      "id": 639601,
      "avatar_url": "https://avatars3.githubusercontent.com/u/639601?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zcbenz",
      "html_url": "https://github.com/zcbenz",
      "followers_url": "https://api.github.com/users/zcbenz/followers",
      "following_url": "https://api.github.com/users/zcbenz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zcbenz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zcbenz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zcbenz/subscriptions",
      "organizations_url": "https://api.github.com/users/zcbenz/orgs",
      "repos_url": "https://api.github.com/users/zcbenz/repos",
      "events_url": "https://api.github.com/users/zcbenz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zcbenz/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2014-08-07T14:13:52Z",
    "updated_at": "2014-08-07T14:13:52Z",
    "body": "Yeah a new issue for the link error is good.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/51565569",
    "html_url": "https://github.com/electron/electron/issues/553#issuecomment-51565569",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/553",
    "id": 51565569,
    "user": {
      "login": "zcbenz",
      "id": 639601,
      "avatar_url": "https://avatars3.githubusercontent.com/u/639601?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zcbenz",
      "html_url": "https://github.com/zcbenz",
      "followers_url": "https://api.github.com/users/zcbenz/followers",
      "following_url": "https://api.github.com/users/zcbenz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zcbenz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zcbenz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zcbenz/subscriptions",
      "organizations_url": "https://api.github.com/users/zcbenz/orgs",
      "repos_url": "https://api.github.com/users/zcbenz/repos",
      "events_url": "https://api.github.com/users/zcbenz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zcbenz/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2014-08-08T05:46:23Z",
    "updated_at": "2014-08-08T05:46:23Z",
    "body": "I've recreated the zip files with Windows's built-in tool, can you remove the `external_binaries` folder and run `script\\update-external-binaries.py` to see if it works?\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/51566770",
    "html_url": "https://github.com/electron/electron/issues/553#issuecomment-51566770",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/553",
    "id": 51566770,
    "user": {
      "login": "sryze",
      "id": 4525736,
      "avatar_url": "https://avatars0.githubusercontent.com/u/4525736?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sryze",
      "html_url": "https://github.com/sryze",
      "followers_url": "https://api.github.com/users/sryze/followers",
      "following_url": "https://api.github.com/users/sryze/following{/other_user}",
      "gists_url": "https://api.github.com/users/sryze/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sryze/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sryze/subscriptions",
      "organizations_url": "https://api.github.com/users/sryze/orgs",
      "repos_url": "https://api.github.com/users/sryze/repos",
      "events_url": "https://api.github.com/users/sryze/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sryze/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-08-08T06:11:11Z",
    "updated_at": "2014-08-08T06:11:11Z",
    "body": "Found the source of the problem, see my PR #564.\n"
  }
]