[
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/267010346",
    "html_url": "https://github.com/electron/electron/issues/8205#issuecomment-267010346",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8205",
    "id": 267010346,
    "user": {
      "login": "MarshallOfSound",
      "id": 6634592,
      "avatar_url": "https://avatars0.githubusercontent.com/u/6634592?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MarshallOfSound",
      "html_url": "https://github.com/MarshallOfSound",
      "followers_url": "https://api.github.com/users/MarshallOfSound/followers",
      "following_url": "https://api.github.com/users/MarshallOfSound/following{/other_user}",
      "gists_url": "https://api.github.com/users/MarshallOfSound/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MarshallOfSound/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MarshallOfSound/subscriptions",
      "organizations_url": "https://api.github.com/users/MarshallOfSound/orgs",
      "repos_url": "https://api.github.com/users/MarshallOfSound/repos",
      "events_url": "https://api.github.com/users/MarshallOfSound/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MarshallOfSound/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-12-14T11:23:50Z",
    "updated_at": "2016-12-14T11:23:50Z",
    "body": "@paul321 I was under the impression this issue had been fixed in `1.4.11` can you verify you are indeed on that version (clean install to double check).\r\n\r\nAlso I am unable to reproduce on `1.4.11`.  My testing code is this.\r\n\r\n```js\r\nsetInterval(() => {\r\n  var session = require('electron').remote.session;\r\n  session.defaultSession.cookies.get({ url: 'https://ffo.com' }, function(err, domainCookies) {});\r\n  console.info('run')\r\n}, 1)\r\n```\r\n\r\nWhich I let run almost 100,000 times with no errors.  Can you provide a reproducible example?"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/267011818",
    "html_url": "https://github.com/electron/electron/issues/8205#issuecomment-267011818",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8205",
    "id": 267011818,
    "user": {
      "login": "paul321",
      "id": 555502,
      "avatar_url": "https://avatars0.githubusercontent.com/u/555502?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paul321",
      "html_url": "https://github.com/paul321",
      "followers_url": "https://api.github.com/users/paul321/followers",
      "following_url": "https://api.github.com/users/paul321/following{/other_user}",
      "gists_url": "https://api.github.com/users/paul321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paul321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paul321/subscriptions",
      "organizations_url": "https://api.github.com/users/paul321/orgs",
      "repos_url": "https://api.github.com/users/paul321/repos",
      "events_url": "https://api.github.com/users/paul321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paul321/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-12-14T11:32:30Z",
    "updated_at": "2016-12-14T11:32:30Z",
    "body": "It's not happening all the time and it's random, sometime is the cookies that cannot be found sometimes other remote object, i'm trying to figure out when it does, I'm on 1.4.11"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/269950911",
    "html_url": "https://github.com/electron/electron/issues/8205#issuecomment-269950911",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8205",
    "id": 269950911,
    "user": {
      "login": "AoDev",
      "id": 1526150,
      "avatar_url": "https://avatars2.githubusercontent.com/u/1526150?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/AoDev",
      "html_url": "https://github.com/AoDev",
      "followers_url": "https://api.github.com/users/AoDev/followers",
      "following_url": "https://api.github.com/users/AoDev/following{/other_user}",
      "gists_url": "https://api.github.com/users/AoDev/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/AoDev/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/AoDev/subscriptions",
      "organizations_url": "https://api.github.com/users/AoDev/orgs",
      "repos_url": "https://api.github.com/users/AoDev/repos",
      "events_url": "https://api.github.com/users/AoDev/events{/privacy}",
      "received_events_url": "https://api.github.com/users/AoDev/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-01-02T09:48:51Z",
    "updated_at": "2017-01-02T09:48:51Z",
    "body": "Hi. I'd like to say that I have the same error with a different process.\r\nIn my case.  `Cannot get property format on missing remote object`. \r\n\r\nI am using: \r\n```\r\n\"electron\": \"1.4.13\",\r\n\"electron-builder\": \"10.15.1\",\r\n```\r\n\r\nIt is also \"random\".\r\nThat's the reason why I can't paste the error stacktrace now. I have relaunched the process multiple times but, obviously, it had to work fine for now. I will try to reproduce it later and give more info.\r\n\r\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/269971786",
    "html_url": "https://github.com/electron/electron/issues/8205#issuecomment-269971786",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8205",
    "id": 269971786,
    "user": {
      "login": "AoDev",
      "id": 1526150,
      "avatar_url": "https://avatars2.githubusercontent.com/u/1526150?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/AoDev",
      "html_url": "https://github.com/AoDev",
      "followers_url": "https://api.github.com/users/AoDev/followers",
      "following_url": "https://api.github.com/users/AoDev/following{/other_user}",
      "gists_url": "https://api.github.com/users/AoDev/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/AoDev/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/AoDev/subscriptions",
      "organizations_url": "https://api.github.com/users/AoDev/orgs",
      "repos_url": "https://api.github.com/users/AoDev/repos",
      "events_url": "https://api.github.com/users/AoDev/events{/privacy}",
      "received_events_url": "https://api.github.com/users/AoDev/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-01-02T13:21:37Z",
    "updated_at": "2017-01-02T13:21:37Z",
    "body": "Ok, finally I could reproduce it. I have no idea why it \"failed\" this time.\r\n\r\nHere is the stacktrace:\r\n\r\n```\r\nUncaught Error: Cannot get property 'format' on missing remote object 246438\r\nError: Cannot get property 'format' on missing remote object 246438\r\n    at throwRPCError (/Applications/Kaiku.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)\r\n    at EventEmitter.<anonymous> (/Applications/Kaiku.app/Contents/Resources/electron.asar/browser/rpc-server.js:368:7)\r\n    at emitThree (events.js:116:13)\r\n    at EventEmitter.emit (events.js:194:7)\r\n    at WebContents.<anonymous> (/Applications/Kaiku.app/Contents/Resources/electron.asar/browser/api/web-contents.js:231:13)\r\n    at emitTwo (events.js:106:13)\r\n    at WebContents.emit (events.js:191:7)\r\n```\r\n\r\nHere is the code that is probably failing but I can't be 100% sure.\r\nNote, I was rewriting my app, some of this code is still legacy. This didn't happen before.\r\n\r\nBasically, I call a library method that:\r\n\r\n- should scan the filesystem\r\n- push a task in a queue for each file found\r\n- run the callback for each file, one after another\r\n\r\nThis is a code running in the renderer process:\r\n_library.js_\r\n```\r\nconst scanner = remote.require('./lib/libraryScanner')\r\n...\r\nscanner.scan(...)\r\n...\r\n // save data in webSQL\r\n  function saveToDb () {\r\n    coverFormat = metadata.picture.length ? metadata.picture[0].format : null\r\n    ...\r\n  }\r\n...\r\n```\r\nWhat I think is failing, per the error message: `metadata.picture[0].format`\r\n\r\n_libraryScanner.js_\r\nThis particular bit, I am not too sure how Electron handles it. If it runs on the main process because I call it with `remote.require('./lib/libraryScanner')` as I assumed. But maybe I am doing something wrong.\r\n\r\n```\r\nvar fs = require('fs')\r\nvar mm = require('musicmetadata')\r\nvar filewalker = require('filewalker')\r\nvar async = require('async')\r\n\r\nfunction scan (folder, onMetadata, onComplete) {\r\n\r\n  function processFile (filePath, qNext) {\r\n    const stream = fs.createReadStream(filePath)\r\n    mm(stream, function (err, metadata) {\r\n      if (!err) {\r\n        metadata.filePath = filePath\r\n        stream.close()\r\n        onMetadata(metadata, function () {\r\n          qNext()\r\n        })\r\n      }\r\n      else {\r\n        qNext()\r\n      }\r\n    })\r\n  }\r\n\r\n  /**\r\n   * Use an asynchronous queue to handle the data process\r\n   * @see  https://github.com/caolan/async#queue\r\n   */\r\n  const q = async.queue(processFile, 1)\r\n\r\n  function addToQueue (p, s, fullPath) {\r\n    q.push(fullPath)\r\n  }\r\n\r\n  function handleError (err) {\r\n    console.log(err)\r\n    onComplete(err)\r\n  }\r\n\r\n  function onAllFilesFound () {\r\n    q.drain = onComplete\r\n    found = this.files\r\n  }\r\n\r\n  filewalker(folder)\r\n    .on('file', addToQueue)\r\n    .on('error', handleError)\r\n    .on('done', onAllFilesFound)\r\n    .walk()\r\n}\r\n```"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/270558512",
    "html_url": "https://github.com/electron/electron/issues/8205#issuecomment-270558512",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8205",
    "id": 270558512,
    "user": {
      "login": "ccnokes",
      "id": 1610343,
      "avatar_url": "https://avatars3.githubusercontent.com/u/1610343?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ccnokes",
      "html_url": "https://github.com/ccnokes",
      "followers_url": "https://api.github.com/users/ccnokes/followers",
      "following_url": "https://api.github.com/users/ccnokes/following{/other_user}",
      "gists_url": "https://api.github.com/users/ccnokes/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ccnokes/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ccnokes/subscriptions",
      "organizations_url": "https://api.github.com/users/ccnokes/orgs",
      "repos_url": "https://api.github.com/users/ccnokes/repos",
      "events_url": "https://api.github.com/users/ccnokes/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ccnokes/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-01-05T03:58:36Z",
    "updated_at": "2017-01-05T03:58:36Z",
    "body": "I've been having this same error too -- I get `Error: Cannot call function 'reload' on missing remote object 12` and it traces back to a call to `webview.reload()`. I can't reproduce it consistently. I'm not sure why `objects-registry`  would be removing/losing a reference.  "
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/271786898",
    "html_url": "https://github.com/electron/electron/issues/8205#issuecomment-271786898",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8205",
    "id": 271786898,
    "user": {
      "login": "chance-an",
      "id": 1046489,
      "avatar_url": "https://avatars0.githubusercontent.com/u/1046489?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chance-an",
      "html_url": "https://github.com/chance-an",
      "followers_url": "https://api.github.com/users/chance-an/followers",
      "following_url": "https://api.github.com/users/chance-an/following{/other_user}",
      "gists_url": "https://api.github.com/users/chance-an/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chance-an/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chance-an/subscriptions",
      "organizations_url": "https://api.github.com/users/chance-an/orgs",
      "repos_url": "https://api.github.com/users/chance-an/repos",
      "events_url": "https://api.github.com/users/chance-an/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chance-an/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-01-11T06:10:18Z",
    "updated_at": "2017-01-11T06:10:18Z",
    "body": "I also encountered this issue while interacting with some file related APIs and `musicmetadata`. I could work around it by [deepcopying](https://www.npmjs.com/package/deepcopy) it after received the data in the renderer process. I also noticed significant performance boost after deepcopying.\r\n\r\nOf course it might not work if you need to use the method/function calls on the received data object."
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/273465706",
    "html_url": "https://github.com/electron/electron/issues/8205#issuecomment-273465706",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8205",
    "id": 273465706,
    "user": {
      "login": "HitomiTenshi",
      "id": 7304212,
      "avatar_url": "https://avatars2.githubusercontent.com/u/7304212?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/HitomiTenshi",
      "html_url": "https://github.com/HitomiTenshi",
      "followers_url": "https://api.github.com/users/HitomiTenshi/followers",
      "following_url": "https://api.github.com/users/HitomiTenshi/following{/other_user}",
      "gists_url": "https://api.github.com/users/HitomiTenshi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/HitomiTenshi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/HitomiTenshi/subscriptions",
      "organizations_url": "https://api.github.com/users/HitomiTenshi/orgs",
      "repos_url": "https://api.github.com/users/HitomiTenshi/repos",
      "events_url": "https://api.github.com/users/HitomiTenshi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/HitomiTenshi/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-01-18T12:43:00Z",
    "updated_at": "2017-01-18T12:43:00Z",
    "body": "I'm struggling with the same issue here. It happens randomly and I can't exactly reproduce it every time. It just happens sometimes:\r\n\r\n```\r\nzone.min.js:1 Uncaught Error: Error in file:///C:/Users/johann.rekowski/Documents/Apps/app/src/app/components/home/home.component.html:25:17 caused by: Cannot call function 'isMaximized' on missing remote object 3\r\nError: Cannot call function 'isMaximized' on missing remote object 3\r\n    at throwRPCError (C:\\Users\\johann.rekowski\\Documents\\Apps\\app\\node_modules\\electron\\dist\\resources\\electron.asar\\browser\\rpc-server.js:143:17)\r\n    at EventEmitter.<anonymous> (C:\\Users\\johann.rekowski\\Documents\\Apps\\app\\node_modules\\electron\\dist\\resources\\electron.asar\\browser\\rpc-server.js:339:7)\r\n    at emitMany (events.js:127:13)\r\n    at EventEmitter.emit (events.js:201:7)\r\n    at WebContents.<anonymous> (C:\\Users\\johann.rekowski\\Documents\\Apps\\app\\node_modules\\electron\\dist\\resources\\electron.asar\\browser\\api\\web-contents.js:231:13)\r\n    at emitTwo (events.js:106:13)\r\n    at WebContents.emit (events.js:191:7)\r\n```"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/276767823",
    "html_url": "https://github.com/electron/electron/issues/8205#issuecomment-276767823",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8205",
    "id": 276767823,
    "user": {
      "login": "neurosnap",
      "id": 1940365,
      "avatar_url": "https://avatars2.githubusercontent.com/u/1940365?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/neurosnap",
      "html_url": "https://github.com/neurosnap",
      "followers_url": "https://api.github.com/users/neurosnap/followers",
      "following_url": "https://api.github.com/users/neurosnap/following{/other_user}",
      "gists_url": "https://api.github.com/users/neurosnap/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/neurosnap/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/neurosnap/subscriptions",
      "organizations_url": "https://api.github.com/users/neurosnap/orgs",
      "repos_url": "https://api.github.com/users/neurosnap/repos",
      "events_url": "https://api.github.com/users/neurosnap/events{/privacy}",
      "received_events_url": "https://api.github.com/users/neurosnap/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-02-01T20:11:00Z",
    "updated_at": "2017-02-01T20:11:17Z",
    "body": "I'm seeing this issue as well, any updates on this? v1.4.13"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/276769286",
    "html_url": "https://github.com/electron/electron/issues/8205#issuecomment-276769286",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8205",
    "id": 276769286,
    "user": {
      "login": "kevinsawicki",
      "id": 671378,
      "avatar_url": "https://avatars0.githubusercontent.com/u/671378?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevinsawicki",
      "html_url": "https://github.com/kevinsawicki",
      "followers_url": "https://api.github.com/users/kevinsawicki/followers",
      "following_url": "https://api.github.com/users/kevinsawicki/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevinsawicki/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevinsawicki/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevinsawicki/subscriptions",
      "organizations_url": "https://api.github.com/users/kevinsawicki/orgs",
      "repos_url": "https://api.github.com/users/kevinsawicki/repos",
      "events_url": "https://api.github.com/users/kevinsawicki/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevinsawicki/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2017-02-01T20:16:45Z",
    "updated_at": "2017-02-01T20:16:45Z",
    "body": "Is anyone able to provide a code sample that reproduces this? Would be happy to take a look but I've been unable to reproduce this since the the last fix for it."
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/276770168",
    "html_url": "https://github.com/electron/electron/issues/8205#issuecomment-276770168",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8205",
    "id": 276770168,
    "user": {
      "login": "HitomiTenshi",
      "id": 7304212,
      "avatar_url": "https://avatars2.githubusercontent.com/u/7304212?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/HitomiTenshi",
      "html_url": "https://github.com/HitomiTenshi",
      "followers_url": "https://api.github.com/users/HitomiTenshi/followers",
      "following_url": "https://api.github.com/users/HitomiTenshi/following{/other_user}",
      "gists_url": "https://api.github.com/users/HitomiTenshi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/HitomiTenshi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/HitomiTenshi/subscriptions",
      "organizations_url": "https://api.github.com/users/HitomiTenshi/orgs",
      "repos_url": "https://api.github.com/users/HitomiTenshi/repos",
      "events_url": "https://api.github.com/users/HitomiTenshi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/HitomiTenshi/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-02-01T20:19:53Z",
    "updated_at": "2017-02-01T20:19:53Z",
    "body": "I fixed my issue by using `ipcMain` and `ipcRenderer`. Using the remote object directly from the renderer thread seems to cause some bugs."
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/276770878",
    "html_url": "https://github.com/electron/electron/issues/8205#issuecomment-276770878",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8205",
    "id": 276770878,
    "user": {
      "login": "kevinsawicki",
      "id": 671378,
      "avatar_url": "https://avatars0.githubusercontent.com/u/671378?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevinsawicki",
      "html_url": "https://github.com/kevinsawicki",
      "followers_url": "https://api.github.com/users/kevinsawicki/followers",
      "following_url": "https://api.github.com/users/kevinsawicki/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevinsawicki/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevinsawicki/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevinsawicki/subscriptions",
      "organizations_url": "https://api.github.com/users/kevinsawicki/orgs",
      "repos_url": "https://api.github.com/users/kevinsawicki/repos",
      "events_url": "https://api.github.com/users/kevinsawicki/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevinsawicki/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2017-02-01T20:22:37Z",
    "updated_at": "2017-02-01T20:22:37Z",
    "body": "> Using the remote object directly from the renderer thread seems to cause some bugs.\r\n\r\nYes, that is true, the `missing remote object` exception only occurs for objects, properties, methods accessed via the `remote` API.\r\n\r\nUntil the `remote` issue is resolved, switching code from using `remote`  to `ipcMain`/`ipcRenderer` will prevent the exception from being thrown."
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/276771722",
    "html_url": "https://github.com/electron/electron/issues/8205#issuecomment-276771722",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8205",
    "id": 276771722,
    "user": {
      "login": "ccnokes",
      "id": 1610343,
      "avatar_url": "https://avatars3.githubusercontent.com/u/1610343?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ccnokes",
      "html_url": "https://github.com/ccnokes",
      "followers_url": "https://api.github.com/users/ccnokes/followers",
      "following_url": "https://api.github.com/users/ccnokes/following{/other_user}",
      "gists_url": "https://api.github.com/users/ccnokes/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ccnokes/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ccnokes/subscriptions",
      "organizations_url": "https://api.github.com/users/ccnokes/orgs",
      "repos_url": "https://api.github.com/users/ccnokes/repos",
      "events_url": "https://api.github.com/users/ccnokes/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ccnokes/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-02-01T20:25:51Z",
    "updated_at": "2017-02-01T20:25:51Z",
    "body": "@kevinsawicki what is the `remote` issue? "
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/276774806",
    "html_url": "https://github.com/electron/electron/issues/8205#issuecomment-276774806",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8205",
    "id": 276774806,
    "user": {
      "login": "kevinsawicki",
      "id": 671378,
      "avatar_url": "https://avatars0.githubusercontent.com/u/671378?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevinsawicki",
      "html_url": "https://github.com/kevinsawicki",
      "followers_url": "https://api.github.com/users/kevinsawicki/followers",
      "following_url": "https://api.github.com/users/kevinsawicki/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevinsawicki/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevinsawicki/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevinsawicki/subscriptions",
      "organizations_url": "https://api.github.com/users/kevinsawicki/orgs",
      "repos_url": "https://api.github.com/users/kevinsawicki/repos",
      "events_url": "https://api.github.com/users/kevinsawicki/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevinsawicki/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2017-02-01T20:38:13Z",
    "updated_at": "2017-02-01T20:38:13Z",
    "body": ">  what is the remote issue?\r\n\r\nThe issue is that remote objects are somehow being incorrectly removed from the objects registry in the main process even though they are still referenced in the renderer process.\r\n\r\nThe stack traces people are seeing in this issue is what happens when this problem occurs, a remote object is accessed but the main process does not have it in its object registry so it is unable to call or access the requested method or property and so it throws this missing object error."
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/276776174",
    "html_url": "https://github.com/electron/electron/issues/8205#issuecomment-276776174",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8205",
    "id": 276776174,
    "user": {
      "login": "ccnokes",
      "id": 1610343,
      "avatar_url": "https://avatars3.githubusercontent.com/u/1610343?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ccnokes",
      "html_url": "https://github.com/ccnokes",
      "followers_url": "https://api.github.com/users/ccnokes/followers",
      "following_url": "https://api.github.com/users/ccnokes/following{/other_user}",
      "gists_url": "https://api.github.com/users/ccnokes/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ccnokes/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ccnokes/subscriptions",
      "organizations_url": "https://api.github.com/users/ccnokes/orgs",
      "repos_url": "https://api.github.com/users/ccnokes/repos",
      "events_url": "https://api.github.com/users/ccnokes/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ccnokes/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-02-01T20:43:33Z",
    "updated_at": "2017-02-01T20:43:33Z",
    "body": "Yeah, that's exactly what's going on for me. Is there an open issue/in-progress PR somewhere for that that I can track? (Or maybe this is it?) \r\n\r\nLet me know if there's any additional info I can provide to help or if there any workarounds for it 😸 "
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/276776829",
    "html_url": "https://github.com/electron/electron/issues/8205#issuecomment-276776829",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8205",
    "id": 276776829,
    "user": {
      "login": "kevinsawicki",
      "id": 671378,
      "avatar_url": "https://avatars0.githubusercontent.com/u/671378?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevinsawicki",
      "html_url": "https://github.com/kevinsawicki",
      "followers_url": "https://api.github.com/users/kevinsawicki/followers",
      "following_url": "https://api.github.com/users/kevinsawicki/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevinsawicki/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevinsawicki/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevinsawicki/subscriptions",
      "organizations_url": "https://api.github.com/users/kevinsawicki/orgs",
      "repos_url": "https://api.github.com/users/kevinsawicki/repos",
      "events_url": "https://api.github.com/users/kevinsawicki/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevinsawicki/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2017-02-01T20:46:01Z",
    "updated_at": "2017-02-01T20:46:01Z",
    "body": "> Or maybe this is it?\r\n\r\nThis is the issue to track this error down.\r\n\r\n> Let me know if there's any additional info I can provide to help or if there any workarounds for it\r\n\r\nAre able to reproduce it (even if only 1 out of X number of times) with a smallish code example that you could provide here?"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/276778610",
    "html_url": "https://github.com/electron/electron/issues/8205#issuecomment-276778610",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8205",
    "id": 276778610,
    "user": {
      "login": "ccnokes",
      "id": 1610343,
      "avatar_url": "https://avatars3.githubusercontent.com/u/1610343?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ccnokes",
      "html_url": "https://github.com/ccnokes",
      "followers_url": "https://api.github.com/users/ccnokes/followers",
      "following_url": "https://api.github.com/users/ccnokes/following{/other_user}",
      "gists_url": "https://api.github.com/users/ccnokes/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ccnokes/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ccnokes/subscriptions",
      "organizations_url": "https://api.github.com/users/ccnokes/orgs",
      "repos_url": "https://api.github.com/users/ccnokes/repos",
      "events_url": "https://api.github.com/users/ccnokes/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ccnokes/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-02-01T20:52:36Z",
    "updated_at": "2017-02-01T20:52:36Z",
    "body": "> smallish code example\r\n\r\nI'll see what I can do... it might be a few days before I can get back to you on that. Like others, when the error happens, it seems to be sort of random. I.e. its working just fine and then all of the sudden I get the `missing remote object` error. I'll try to track it down though. Thanks! "
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/276782046",
    "html_url": "https://github.com/electron/electron/issues/8205#issuecomment-276782046",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8205",
    "id": 276782046,
    "user": {
      "login": "AoDev",
      "id": 1526150,
      "avatar_url": "https://avatars2.githubusercontent.com/u/1526150?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/AoDev",
      "html_url": "https://github.com/AoDev",
      "followers_url": "https://api.github.com/users/AoDev/followers",
      "following_url": "https://api.github.com/users/AoDev/following{/other_user}",
      "gists_url": "https://api.github.com/users/AoDev/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/AoDev/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/AoDev/subscriptions",
      "organizations_url": "https://api.github.com/users/AoDev/orgs",
      "repos_url": "https://api.github.com/users/AoDev/repos",
      "events_url": "https://api.github.com/users/AoDev/events{/privacy}",
      "received_events_url": "https://api.github.com/users/AoDev/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-02-01T21:05:31Z",
    "updated_at": "2017-02-01T21:05:31Z",
    "body": "My 2 cents, it could be garbage collector related. I have changed my process to make it much less memory intensive and the error does not happen anymore. That's also why it can be random, garbage collection may be triggered at any time. But I have nothing to prove this theory right now."
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/295269328",
    "html_url": "https://github.com/electron/electron/issues/8205#issuecomment-295269328",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8205",
    "id": 295269328,
    "user": {
      "login": "BrandonSmith",
      "id": 10338,
      "avatar_url": "https://avatars0.githubusercontent.com/u/10338?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/BrandonSmith",
      "html_url": "https://github.com/BrandonSmith",
      "followers_url": "https://api.github.com/users/BrandonSmith/followers",
      "following_url": "https://api.github.com/users/BrandonSmith/following{/other_user}",
      "gists_url": "https://api.github.com/users/BrandonSmith/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/BrandonSmith/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/BrandonSmith/subscriptions",
      "organizations_url": "https://api.github.com/users/BrandonSmith/orgs",
      "repos_url": "https://api.github.com/users/BrandonSmith/repos",
      "events_url": "https://api.github.com/users/BrandonSmith/events{/privacy}",
      "received_events_url": "https://api.github.com/users/BrandonSmith/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-04-19T13:25:58Z",
    "updated_at": "2017-04-19T13:26:13Z",
    "body": "FWIW... I cannot reproduce locally, but my error catcher for a deployed app in the field periodically catches the following...\r\n\r\n`Cannot call function 'setBadgeCount' on missing remote object`\r\n\r\n...on the call...\r\n\r\n`remote.app.setBadgeCount(count)`\r\n\r\nI can go the `ipc` route, but it seems odd that the `app` property goes missing."
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/297777082",
    "html_url": "https://github.com/electron/electron/issues/8205#issuecomment-297777082",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8205",
    "id": 297777082,
    "user": {
      "login": "thomasmeadows",
      "id": 11771776,
      "avatar_url": "https://avatars0.githubusercontent.com/u/11771776?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thomasmeadows",
      "html_url": "https://github.com/thomasmeadows",
      "followers_url": "https://api.github.com/users/thomasmeadows/followers",
      "following_url": "https://api.github.com/users/thomasmeadows/following{/other_user}",
      "gists_url": "https://api.github.com/users/thomasmeadows/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thomasmeadows/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thomasmeadows/subscriptions",
      "organizations_url": "https://api.github.com/users/thomasmeadows/orgs",
      "repos_url": "https://api.github.com/users/thomasmeadows/repos",
      "events_url": "https://api.github.com/users/thomasmeadows/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thomasmeadows/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-04-27T17:03:17Z",
    "updated_at": "2017-04-27T17:03:17Z",
    "body": "same issue here, kinda random at app boot time"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/297784174",
    "html_url": "https://github.com/electron/electron/issues/8205#issuecomment-297784174",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8205",
    "id": 297784174,
    "user": {
      "login": "ccnokes",
      "id": 1610343,
      "avatar_url": "https://avatars3.githubusercontent.com/u/1610343?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ccnokes",
      "html_url": "https://github.com/ccnokes",
      "followers_url": "https://api.github.com/users/ccnokes/followers",
      "following_url": "https://api.github.com/users/ccnokes/following{/other_user}",
      "gists_url": "https://api.github.com/users/ccnokes/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ccnokes/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ccnokes/subscriptions",
      "organizations_url": "https://api.github.com/users/ccnokes/orgs",
      "repos_url": "https://api.github.com/users/ccnokes/repos",
      "events_url": "https://api.github.com/users/ccnokes/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ccnokes/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-04-27T17:29:56Z",
    "updated_at": "2017-04-27T17:31:02Z",
    "body": "Just reporting back here, I've never been able to reproduce this one. However, I did discover a memory leak in my app caused by `webview` DOM getting destroyed before I had a chance to clean up some resources associated with it, i.e. `webview.webContents.session.webRequest.onErrorOccurred(null)`, etc. It seems that if the DOM for a webview is destroyed then you lose your handle on it's webContents too, so the above call errors out, and you get a leak. \r\n\r\nSo basically, being extra diligent in checking for leaks helped me solve this issue. It's easy to leak things with event emitters (a lot of Electron APIs are event emitters) especially. Hopefully this helps someone. "
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/305449275",
    "html_url": "https://github.com/electron/electron/issues/8205#issuecomment-305449275",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8205",
    "id": 305449275,
    "user": {
      "login": "zcbenz",
      "id": 639601,
      "avatar_url": "https://avatars3.githubusercontent.com/u/639601?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zcbenz",
      "html_url": "https://github.com/zcbenz",
      "followers_url": "https://api.github.com/users/zcbenz/followers",
      "following_url": "https://api.github.com/users/zcbenz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zcbenz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zcbenz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zcbenz/subscriptions",
      "organizations_url": "https://api.github.com/users/zcbenz/orgs",
      "repos_url": "https://api.github.com/users/zcbenz/repos",
      "events_url": "https://api.github.com/users/zcbenz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zcbenz/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2017-06-01T10:05:39Z",
    "updated_at": "2017-06-01T10:05:39Z",
    "body": "I believe we have already a few bugs may cause this issue in recent versions, I'm closing this issue now but if anyone still sees in v1.7.x, please report back and I'll reopen."
  }
]