[
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/306668498",
    "html_url": "https://github.com/electron/electron/issues/9685#issuecomment-306668498",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/9685",
    "id": 306668498,
    "user": {
      "login": "MarshallOfSound",
      "id": 6634592,
      "avatar_url": "https://avatars0.githubusercontent.com/u/6634592?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MarshallOfSound",
      "html_url": "https://github.com/MarshallOfSound",
      "followers_url": "https://api.github.com/users/MarshallOfSound/followers",
      "following_url": "https://api.github.com/users/MarshallOfSound/following{/other_user}",
      "gists_url": "https://api.github.com/users/MarshallOfSound/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MarshallOfSound/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MarshallOfSound/subscriptions",
      "organizations_url": "https://api.github.com/users/MarshallOfSound/orgs",
      "repos_url": "https://api.github.com/users/MarshallOfSound/repos",
      "events_url": "https://api.github.com/users/MarshallOfSound/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MarshallOfSound/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-06-07T02:30:14Z",
    "updated_at": "2017-06-07T02:30:14Z",
    "body": "@Zyles That is a `standard` linting error as callback's in a node.js world typically are of the format\r\n\r\n```js\r\ncallback(error, result)\r\n```\r\n\r\nIn this API's case it is simply\r\n\r\n```js\r\ncallback(result)\r\n```\r\n\r\nand standard doesn't like it, you should either add an exception or disable that rule.  This isn't an error with Electron üëç "
  }
]